import Head from 'next/head'
import {Header} from '../components/Header';
import {Post} from '../components/Post';
import {LeftMenu} from '../components/LeftMenu'

export default function Home() {
  return (
    <div>
      <Head>
        <title>RJournal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Flex:opsz,wght@8..144,100;8..144,200;8..144,300;8..144,400;8..144,500;8..144,700;8..144,900;8..144,1000&display=swap" rel="stylesheet"></link>
      </Head>
     <Header/>
     <div className='wrapper'>
       <div className="leftside"><LeftMenu/></div>
       <div className='content'><Post /> </div>
       <div className="rightside"></div>
     </div>
    </div>
  )
}
